TestWebApp/Models/ErrorViewModel.cs
using System;

namespace TestWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TestWebApp/Models/Item.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace TestWebApp.Models
{
    public class Item
    {
        [Key]
        public int ItemId { get; set; }

        [Required(ErrorMessage = "Name is required!")]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Price is required!")]
        [Display(Name = "Price")]
        public double Price { get; set; }

        [Required(ErrorMessage = "Amount is required!")]
        [Display(Name = "Quantity")]
        public int Amount { get; set; }

        [Required(ErrorMessage = "Stock amount is required!")]
        [Display(Name = "Stock Amount")]
        public int Stock { get; set; }

        [Required(ErrorMessage = "Sell amount is required!")]
        [Display(Name = "Sell Amount")]
        public int Sell { get; set; }

        public string ItemImageURL { get; set; }

        [NotMapped]
        /*[Required(ErrorMessage = "Profile image is required!")]*/
        [Display(Name = "Upload Image of the Product")]
        public IFormFile ImageFile { get; set; }
    }
}

TestWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TestWebApp.Models;

namespace TestWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }


        public IActionResult Index()
        {
            return View();
        }

        /*public IActionResult Privacy()
        {
            return View();
        }*/

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestWebApp/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using TestWebApp.Data.Services;
using TestWebApp.Models;

namespace TestWebApp.Controllers
{
    public class ItemsController : Controller
    {
        private readonly IItemsService _service;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ItemsController(IItemsService service, IWebHostEnvironment hostEnvironment)
        {
            _service = service;
            this._hostEnvironment = hostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name, Price, Amount, Sell, ImageFile")] Item item) 
        {
            if (ModelState.IsValid) 
            {
                item.Stock = item.Amount - item.Sell;


                string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(item.ImageFile.FileName);
                string extension = Path.GetExtension(item.ImageFile.FileName);
                item.ItemImageURL = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                string path = Path.Combine(wwwRootPath + "/images/", fileName);
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await item.ImageFile.CopyToAsync(fileStream);
                }


                await _service.AddAsync(item);
                return RedirectToAction(nameof(Index));
            }

            return View(item);
        }


        /*public async Task<IActionResult> Details(int id)
        {
            var itemDetails = _service.GetByIdAsync(id);

            if (itemDetails == null) return View("NotFound");

            return View(itemDetails);

        }*/



       /* public async Task<IActionResult> Edit(int id)
        {
            var itemDetails = await _service.GetByIdAsync(id);

            if (itemDetails == null) return View("NotFound");

            return View(itemDetails);
            return View(itemDetails);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ItemId, Name, Price, Amount, Sell")] Item item)
        {

            if (ModelState.IsValid)
            {
                item.Stock = item.Amount - item.Sell;

                await _service.UpdateAsync(id, item);
                return RedirectToAction(nameof(Index));
            }

            return View(item);
        }*/


        public async Task<IActionResult> Stock()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        public async Task<IActionResult> Shop()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }
    }
}

TestWebApp/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    ViewData["Title"] = "Home Page";
}

@if (SignInManager.IsSignedIn(User))
{
    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <div class="mt-5">
            <a class="btn btn-primary" asp-area="" asp-controller="Items" asp-action="Create">Add Product</a>
        </div>
    </div>
}

else
{
    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <p>Please Login if you want to add or view products. If you don't have an account, register first.</p>
    </div>
}

TestWebApp/Views/Items/Create.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


@model Item


@{
    ViewData["Title"] = "List of Items";
}


@if (SignInManager.IsSignedIn(User))
{
<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1 class="display-4">Add new Product</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Price" class="control-label"></label>
                        <input asp-for="Price" class="form-control" />
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Amount" class="control-label"></label>
                        <input asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>
                    @*<div class="form-group">
                        <label asp-for="Stock" class="control-label"></label>
                        <input asp-for="Stock" class="form-control" />
                        <span asp-validation-for="Stock" class="text-danger"></span>
                    </div>*@
                    <div class="form-group">
                        <label asp-for="Sell" class="control-label"></label>
                        <input asp-for="Sell" class="form-control" />
                        <span asp-validation-for="Sell" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ImageFile" class="control-label"></label>
                        <input asp-for="ImageFile" class="form-control" accept="image/p*" />
                        <span asp-validation-for="ImageFile" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-5">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All Products</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
}




else 
{
    <div class="text-center">
        <h1 class="display-4">No Access</h1>
        <p>Please Login if you want to add products. If you don't have an account, register first.</p>
    </div>
}

TestWebApp/Views/Items/Edit.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


@model Item


@{
    ViewData["Title"] = "Update";
}


@if (SignInManager.IsSignedIn(User))
{
<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1 class="display-4">Update Product</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Price" class="control-label"></label>
                        <input asp-for="Price" class="form-control" />
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Amount" class="control-label"></label>
                        <input asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Sell" class="control-label"></label>
                        <input asp-for="Sell" class="form-control" />
                        <span asp-validation-for="Sell" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-5">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All Products</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
}




else 
{
    <div class="text-center">
        <h1 class="display-4">No Access</h1>
        <p>Please Login if you want to add products. If you don't have an account, register first.</p>
    </div>
}

TestWebApp/Views/Items/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager



@model IEnumerable<Item>


@{
    ViewData["Title"] = "List of Items";
}

@if (SignInManager.IsSignedIn(User))
{
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-4 col-xs-6 border-primary mb-3">
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-header text-white bg-info">
                                <p class="card-text">
                                    <h5 class="card-title">
                                        @item.Name
                                    </h5>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <img src="@("~/images/"+ item.ItemImageURL)" asp-append-version="true" width="100%" alt="@item.Name">
                        </div>
                        <div class="col-md-6">
                            <div class="card-body">

                                <p class="card-text"><b>Name: </b>@item.Name</p>
                                <p class="card-text"><b>Price: </b>@item.Price</p>
                                <p class="card-text"><b>Amount: </b>@item.Amount</p>
                                <p class="card-text"><b>In Stock: </b>@item.Stock</p>
                                <p class="card-text"><b>In Sell: </b>@item.Sell</p>
                            </div>
                        </div>
                        @*<div class="col-md-12">
                            <div class="card-footer ">
                                <p class="card-text">
                                    <a class="btn btn-outline-primary float-right" asp-controller="Items" asp-action="Edit" asp-route-id="@item.ItemId">Update</a>
                                    <a class="btn btn-danger text-white" asp-action="Details" asp-route-id="@item.ItemId">Details</a>
                                </p>
                            </div>
                        </div>*@
                    </div>
                </div>
            </div>
        }
    </div>

}
else
{
    <div class="text-center">
        <h1 class="display-4">No Access</h1>
        <p>Please Login if you want to add products. If you don't have an account, register first.</p>
    </div>
}

TestWebApp/Views/Items/Index1.cshtml
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@("~/images/"+ item.ItemImageURL)" asp-append-version="true" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">

                            <p class="card-text"><b>Name: </b>@item.Name</p>
                            <p class="card-text"><b>Price: </b>@item.Price</p>
                            <p class="card-text"><b>In Sell: </b>@item.Sell</p>
                        </div>
                    </div>
                    <div class="col-md-12">
                            <div class="card-footer ">
                                <p class="card-text">
                                    <a class="btn btn-outline-primary float-right" href="#">Buy</a>
                                    
                                </p>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    }
</div>

TestWebApp/Views/Items/Shop.cshtml
@model IEnumerable<Item>


@{
    ViewData["Title"] = "List of Items";
}



    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-4 col-xs-6 border-primary mb-3">
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-header text-white bg-info">
                                <p class="card-text">
                                    <h5 class="card-title">
                                        @item.Name
                                    </h5>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <img src="@("~/images/"+ item.ItemImageURL)" asp-append-version="true" width="100%" alt="@item.Name">
                        </div>
                        <div class="col-md-6">
                            <div class="card-body">

                                <p class="card-text"><b>Name: </b>@item.Name</p>
                                <p class="card-text"><b>Price: </b>@item.Price</p>
                                <p class="card-text"><b>In Sell: </b>@item.Sell</p>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="card-footer ">
                                <p class="card-text">
                                    <a class="btn btn-outline-primary float-right mb-2" href="#">Buy</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

TestWebApp/Views/Items/Stock.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager



@model IEnumerable<Item>


@{
    ViewData["Title"] = "List of Items";
}

@if (SignInManager.IsSignedIn(User))
{
    <div class="row">
        @foreach (var item in Model)
        {
        <div class="card ml-2" style="width:300px">
            <div class="card-body">
                <h4 class="card-title">@item.Name</h4>
                <p class="card-text">Quantity in Stock: @item.Stock</p>
                <a href="#" class="btn btn-primary">Update</a>
            </div>
        </div>
        }
    </div>

}
else
{
    <div class="text-center">
        <h1 class="display-4">No Access</h1>
        <p>Please Login if you want to add products. If you don't have an account, register first.</p>
    </div>
}

TestWebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestWebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Index">Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Stock">Stocks</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Shop">Shop</a>
                            </li> 
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            &copy; 2022 - TestWebApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>